// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_Management_Webapp.Migrations
{
    [DbContext(typeof(Gym_Management_WebappContext))]
    [Migration("20260927102146_NguyenDacDat")]
    partial class NguyenDacDat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_Management_Webapp.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            Email = "user1@gmail.com",
                            HoTen = "Admin",
                            MatKhau = "admin123",
                            TenDangNhap = "admin",
                            TrangThai = "Active",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            Email = "user2@gmail.com",
                            HoTen = "User",
                            MatKhau = "user123",
                            TenDangNhap = "user",
                            TrangThai = "Active",
                            VaiTro = "User"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            Email = "user3@gmail.com",
                            HoTen = "User3",
                            MatKhau = "user123",
                            TenDangNhap = "user3",
                            TrangThai = "Active",
                            VaiTro = "User"
                        },
                        new
                        {
                            MaTaiKhoan = 4,
                            Email = "user4@gmail.com",
                            HoTen = "User4",
                            MatKhau = "user123",
                            TenDangNhap = "user4",
                            TrangThai = "Active",
                            VaiTro = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
