// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyPhongTap_UNETI01_TI17A1HN.Migrations
{
    [DbContext(typeof(QuanLyPhongTap_UNETI01_TI17A1HNContext))]
    partial class QuanLyPhongTap_UNETI01_TI17A1HNContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongTap_UNETI01_TI17A1HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            Email = "admingym01@gmail.com",
                            HoTen = "Admin 01",
                            MatKhau = "admin123",
                            TenDangNhap = "admin01",
                            TrangThai = "Lock",
                            VaiTro = "admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            Email = "admingym02@gmail.com",
                            HoTen = "Admin 02",
                            MatKhau = "admin123",
                            TenDangNhap = "admin02",
                            TrangThai = "Unlock",
                            VaiTro = "admin"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            Email = "nguyenvietnguy@gmail.com",
                            HoTen = "Nguyễn Viết Nguy",
                            MatKhau = "hoivien123",
                            TenDangNhap = "hoivien01",
                            TrangThai = "Lock",
                            VaiTro = "hoivien"
                        },
                        new
                        {
                            MaTaiKhoan = 4,
                            Email = "nguyenvanlap@gmail.com",
                            HoTen = "Nguyễn Văn Lập",
                            MatKhau = "hoivien123",
                            TenDangNhap = "hoivien02",
                            TrangThai = "Unlock",
                            VaiTro = "hoivien"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
